### PR TITLE
Added the type function

### PR DESCRIPTION
**Pull request by suzgunmirac**
Hi! I realized that **tensor.type** was initially not working, so I added the **.type** function to _core.py_.

### CODE REVIEW

**Comment by MiroFurtado** [comment]
Should this also support the type-casting ability of the tensor.type function?

**Comment by suzgunmirac** [comment]
Excellent suggestion, Miro! I will try to add that function as well.

**Comment by srush** [comment]
Thanks for the PR. Two things: 

* I think you can just add this function to this list. Any function there will be automatically wrapped (if it doesn't return a tensor) https://github.com/harvardnlp/namedtensor/blob/master/namedtensor/torch_helpers.py#L330

* The idea is that core.py has no pytorch specific functions (i.e. should work for numpy too).

**Comment by suzgunmirac** [comment]
Thanks, @srush! 

I added "type" into the aforementioned list "_info" in _torch_helpers.py_. Your suggestion actually enables us to directly solve the casting problem. 

Here is an example:
```
>>> x = ntorch.randn(3, 3, names=("h", "w"))
>>> x.type()
'torch.FloatTensor'
>>> x1 = x.double()
>>> x1.type()
'torch.DoubleTensor'
>>> x2 = x.type(torch.IntTensor)
>>> x2.type()
'torch.IntTensor'
>>> x.type()
'torch.FloatTensor'
```

**Comment by srush** [comment]
Lol. That was easy!

**Pull request merged**
