### PR TITLE
Adding ntorch.stack

### PR DESCRIPTION
**Pull request by MiroFurtado**
Is it confusing to have a different function with ``a.stack`` vs. ``ntorch.stack(`` which do different things?

### CODE REVIEW

**Comment by MiroFurtado** [comment]
Huh, my checks aren't failing locally. I'm not exactly sure what the bug is

**Comment by srush** [comment]
Looks great. One minor change

* Can you throw a runtime error instead of asserting? Not sure why but that's the torch behavior.

**Comment by MiroFurtado** [comment]
Done! `cat` also has an assert if that'd be a problem

**Comment by srush** [comment]
Excellent. Yes I agree two stacks is bad. It's a numpy versus torch issue. However let's deal with that later.

**Pull request merged**
